// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaxplEmgIiAkz70Y9FZhzAwJwpA_69swg',
    appId: '1:35492176424:web:7a4520941ee412e0418b1d',
    messagingSenderId: '35492176424',
    projectId: 'tashel-a589d',
    authDomain: 'tashel-a589d.firebaseapp.com',
    storageBucket: 'tashel-a589d.firebasestorage.app',
    measurementId: 'G-XLN12S96BL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABWa0LjFrKBQkMSMxPX5yauH6axbOpddk',
    appId: '1:35492176424:android:bcd049064a4ae5e6418b1d',
    messagingSenderId: '35492176424',
    projectId: 'tashel-a589d',
    storageBucket: 'tashel-a589d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0UMHCrlmCpWhr_4Amtjno1e0D4kmEBPY',
    appId: '1:35492176424:ios:dc53b6e07507ec14418b1d',
    messagingSenderId: '35492176424',
    projectId: 'tashel-a589d',
    storageBucket: 'tashel-a589d.firebasestorage.app',
    iosBundleId: 'com.example.fkra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0UMHCrlmCpWhr_4Amtjno1e0D4kmEBPY',
    appId: '1:35492176424:ios:dc53b6e07507ec14418b1d',
    messagingSenderId: '35492176424',
    projectId: 'tashel-a589d',
    storageBucket: 'tashel-a589d.firebasestorage.app',
    iosBundleId: 'com.example.fkra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaxplEmgIiAkz70Y9FZhzAwJwpA_69swg',
    appId: '1:35492176424:web:309e6e9d91bf82d0418b1d',
    messagingSenderId: '35492176424',
    projectId: 'tashel-a589d',
    authDomain: 'tashel-a589d.firebaseapp.com',
    storageBucket: 'tashel-a589d.firebasestorage.app',
    measurementId: 'G-QSY7921S77',
  );
}
