// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzQzw5mNje-Gi32J1VL7Un3IWlfjn-F2Q',
    appId: '1:854204491835:web:0a001ea4bc4a351694141e',
    messagingSenderId: '854204491835',
    projectId: 'tasheel-e4d47',
    authDomain: 'tasheel-e4d47.firebaseapp.com',
    storageBucket: 'tasheel-e4d47.firebasestorage.app',
    measurementId: 'G-XF5L5HWYRM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArRmPcSATyLxmL-CwNiDjZerK0U3-WIFw',
    appId: '1:854204491835:android:d2fea96b2bc290cd94141e',
    messagingSenderId: '854204491835',
    projectId: 'tasheel-e4d47',
    storageBucket: 'tasheel-e4d47.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw9apPyewq1lLge-0SwzGSXKNvCtxcuiQ',
    appId: '1:854204491835:ios:44f47fe0d903c36994141e',
    messagingSenderId: '854204491835',
    projectId: 'tasheel-e4d47',
    storageBucket: 'tasheel-e4d47.firebasestorage.app',
    iosClientId: '854204491835-d2jernf6u2h906dlfnht04hug834bdlh.apps.googleusercontent.com',
    iosBundleId: 'com.example.fkra',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw9apPyewq1lLge-0SwzGSXKNvCtxcuiQ',
    appId: '1:854204491835:ios:44f47fe0d903c36994141e',
    messagingSenderId: '854204491835',
    projectId: 'tasheel-e4d47',
    storageBucket: 'tasheel-e4d47.firebasestorage.app',
    iosClientId: '854204491835-d2jernf6u2h906dlfnht04hug834bdlh.apps.googleusercontent.com',
    iosBundleId: 'com.example.fkra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzQzw5mNje-Gi32J1VL7Un3IWlfjn-F2Q',
    appId: '1:854204491835:web:69da390e98f1a05394141e',
    messagingSenderId: '854204491835',
    projectId: 'tasheel-e4d47',
    authDomain: 'tasheel-e4d47.firebaseapp.com',
    storageBucket: 'tasheel-e4d47.firebasestorage.app',
    measurementId: 'G-7CHC83YEXR',
  );
}
